name: 'mz_segment'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mz_segment'

model-paths: ["sources","models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  mz_segment:
    staging:
      +materialized: view
      +schema: "dbt_{{ env_var('MZ_USER')}}"
    marts:
      +materailized: materializedview
      +schema: "dbt_{{ env_var('MZ_USER')}}"

tests:
  mz_segment:
    +store_failures: true
    +schema: test
